#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from threeaddr.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "threeaddr.y"

	#include<bits/stdc++.h>
	typedef long long ll;
	using namespace std;
	int yylex();
	void yyerror(char *s);
	int tempcount=0;
	int getTemp()
	{
		return tempcount++;
	}
	typedef struct node
	{
		string  addr, array;
		pair<string,vector<ll> > type;
		vector<ll> trueList,falseList,nextList;
		int instNum;
	}NODE;

	NODE* makeNode()
	{
		NODE *temp=new NODE();
		ostringstream ss;
		ss<<"t"<<getTemp();
		temp->addr=ss.str();
		ss.str("");
		temp->array="";
		return temp;
	}
	NODE* makeNode(string *x)
	{
		NODE *temp=new NODE();
		temp->addr=*x;
		temp->array="";
		return temp;
	}

	//for symbol table
	deque<string> s;
	deque<int> vars;
	deque<int> blocks;
	int blocknum=-1,varnum=0;
	map<ll,map<string,pair<pair<string,vector<ll> >,string> > > table;
	map<string,ll> width;
	ll getWidth(pair<string,vector<ll> > type);
	string to_string(ll val);
	void insertID(int bno,string varname);
	void printTable();

	// for backpatch
	int instCounter=0;
	map<ll,string> instList;
	int nextInst();
	vector<ll> merge(vector<ll> a,vector<ll> b);
	void backpatch(vector<ll> list,int num);

#line 58 "threeaddr.y"
typedef union{
	typedef struct node NODE;
	string *str;
	NODE *node;

} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	KEY	258
#define	AND	259
#define	OR	260
#define	NOT	261
#define	RELOP	262
#define	ID	263
#define	VAL	264
#define	SC	265
#define	CM	266
#define	PL	267
#define	MI	268
#define	MUL	269
#define	DIV	270
#define	POW	271
#define	OP	272
#define	CL	273
#define	AO	274
#define	AC	275
#define	EQ	276
#define	BO	277
#define	BC	278
#define	UNR	279
#define	TRUE	280
#define	FALSE	281
#define	IF	282
#define	ELSE	283
#define	WHILE	284


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int KEY;
static const int AND;
static const int OR;
static const int NOT;
static const int RELOP;
static const int ID;
static const int VAL;
static const int SC;
static const int CM;
static const int PL;
static const int MI;
static const int MUL;
static const int DIV;
static const int POW;
static const int OP;
static const int CL;
static const int AO;
static const int AC;
static const int EQ;
static const int BO;
static const int BC;
static const int UNR;
static const int TRUE;
static const int FALSE;
static const int IF;
static const int ELSE;
static const int WHILE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,KEY=258
	,AND=259
	,OR=260
	,NOT=261
	,RELOP=262
	,ID=263
	,VAL=264
	,SC=265
	,CM=266
	,PL=267
	,MI=268
	,MUL=269
	,DIV=270
	,POW=271
	,OP=272
	,CL=273
	,AO=274
	,AC=275
	,EQ=276
	,BO=277
	,BC=278
	,UNR=279
	,TRUE=280
	,FALSE=281
	,IF=282
	,ELSE=283
	,WHILE=284


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::KEY=258;
const int YY_parse_CLASS::AND=259;
const int YY_parse_CLASS::OR=260;
const int YY_parse_CLASS::NOT=261;
const int YY_parse_CLASS::RELOP=262;
const int YY_parse_CLASS::ID=263;
const int YY_parse_CLASS::VAL=264;
const int YY_parse_CLASS::SC=265;
const int YY_parse_CLASS::CM=266;
const int YY_parse_CLASS::PL=267;
const int YY_parse_CLASS::MI=268;
const int YY_parse_CLASS::MUL=269;
const int YY_parse_CLASS::DIV=270;
const int YY_parse_CLASS::POW=271;
const int YY_parse_CLASS::OP=272;
const int YY_parse_CLASS::CL=273;
const int YY_parse_CLASS::AO=274;
const int YY_parse_CLASS::AC=275;
const int YY_parse_CLASS::EQ=276;
const int YY_parse_CLASS::BO=277;
const int YY_parse_CLASS::BC=278;
const int YY_parse_CLASS::UNR=279;
const int YY_parse_CLASS::TRUE=280;
const int YY_parse_CLASS::FALSE=281;
const int YY_parse_CLASS::IF=282;
const int YY_parse_CLASS::ELSE=283;
const int YY_parse_CLASS::WHILE=284;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		107
#define	YYFLAG		-32768
#define	YYNTBASE	30

#define YYTRANSLATE(x) ((unsigned)(x) <= 284 ? yytranslate[x] : 56)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     4,     6,     8,    10,    12,    14,    16,    23,
    34,    42,    43,    48,    52,    54,    55,    61,    64,    69,
    74,    75,    76,    81,    82,    87,    92,    97,   102,   104,
   109,   114,   116,   119,   123,   127,   129,   131,   132,   133,
   137,   141,   143,   145,   149,   153,   155,   159,   161,   165,
   167,   169
};

static const short yyrhs[] = {    -1,
    31,    32,     0,    33,     0,    34,     0,    35,     0,    36,
     0,    45,     0,    39,     0,    27,    17,    48,    18,    50,
    32,     0,    27,    17,    48,    18,    50,    32,    28,    51,
    50,    32,     0,    29,    50,    17,    48,    18,    50,    32,
     0,     0,    22,    37,    38,    23,     0,    38,    50,    32,
     0,    32,     0,     0,     3,    41,    40,    43,    10,     0,
     8,    42,     0,     8,    42,    21,     9,     0,    19,     9,
    20,    42,     0,     0,     0,    11,    41,    44,    43,     0,
     0,    46,    21,    47,    10,     0,     8,    21,    47,    10,
     0,     8,    19,    52,    20,     0,    46,    19,    52,    20,
     0,    52,     0,    48,     5,    50,    49,     0,    48,     4,
    50,    49,     0,    49,     0,     6,    49,     0,    17,    48,
    18,     0,    52,     7,    52,     0,    25,     0,    26,     0,
     0,     0,    52,    12,    53,     0,    52,    13,    53,     0,
    53,     0,    46,     0,    53,    14,    54,     0,    53,    15,
    54,     0,    54,     0,    55,    16,    54,     0,    55,     0,
    17,    52,    18,     0,     8,     0,     9,     0,    13,    55,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    71,    79,    86,    86,    87,    88,    89,    90,    93,    98,
   105,   112,   122,   132,   136,   138,   141,   143,   143,   145,
   145,   147,   150,   150,   152,   152,   161,   171,   182,   185,
   190,   196,   199,   199,   200,   207,   208,   210,   211,   213,
   213,   214,   215,   218,   218,   219,   222,   222,   225,   225,
   232,   233
};

static const char * const yytname[] = {   "$","error","$illegal.","KEY","AND",
"OR","NOT","RELOP","ID","VAL","SC","CM","PL","MI","MUL","DIV","POW","OP","CL",
"AO","AC","EQ","BO","BC","UNR","TRUE","FALSE","IF","ELSE","WHILE","ss","@1",
"stmt","if","ifelse","while","block","@2","stmt_list","decl","@3","id","arr",
"d","@4","a","l","r","bool","bb","m","n","e","t","f","g",""
};
#endif

static const short yyr1[] = {     0,
    31,    30,    32,    32,    32,    32,    32,    32,    33,    34,
    35,    37,    36,    38,    38,    40,    39,    41,    41,    42,
    42,    44,    43,    43,    45,    45,    46,    46,    47,    48,
    48,    48,    49,    49,    49,    49,    49,    50,    51,    52,
    52,    52,    52,    53,    53,    53,    54,    54,    55,    55,
    55,    55
};

static const short yyr2[] = {     0,
     0,     2,     1,     1,     1,     1,     1,     1,     6,    10,
     7,     0,     4,     3,     1,     0,     5,     2,     4,     4,
     0,     0,     4,     0,     4,     4,     4,     4,     1,     4,
     4,     1,     2,     3,     3,     1,     1,     0,     0,     3,
     3,     1,     1,     3,     3,     1,     3,     1,     3,     1,
     1,     2
};

static const short yydefact[] = {     1,
     0,     0,     0,    12,     0,    38,     2,     3,     4,     5,
     6,     8,     7,     0,    21,    16,     0,     0,     0,     0,
     0,     0,     0,     0,    18,    24,    50,    51,     0,     0,
    43,     0,    42,    46,    48,     0,    29,    15,    38,     0,
     0,    36,    37,     0,    32,     0,     0,     0,     0,     0,
     0,     0,     0,    50,    52,     0,     0,     0,    27,     0,
     0,     0,    26,    13,     0,    33,     0,     0,    38,    38,
    38,     0,     0,    28,    25,    21,    19,    22,    17,    49,
    40,    41,    44,    45,    47,    14,    34,     0,     0,     0,
    35,    38,    20,    24,    31,    30,     9,     0,    23,    39,
    11,    38,     0,    10,     0,     0,     0
};

static const short yydefgoto[] = {   105,
     1,     7,     8,     9,    10,    11,    19,    39,    12,    26,
    16,    25,    53,    94,    13,    31,    36,    44,    45,    21,
   102,    46,    33,    34,    35
};

static const short yypact[] = {-32768,
     9,    21,     4,-32768,    18,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,    24,    30,-32768,    13,    13,     9,    31,
    46,    13,    13,    62,    63,    72,    71,-32768,    33,    13,
    74,    39,    60,-32768,    78,    85,    66,-32768,    73,    31,
    31,-32768,-32768,     2,-32768,    69,    31,    57,    88,    79,
    91,    21,    93,-32768,-32768,    48,    33,    33,-32768,    33,
    33,    33,-32768,-32768,     9,-32768,     6,    55,-32768,-32768,
-32768,    13,    10,-32768,-32768,    30,-32768,-32768,-32768,-32768,
    60,    60,-32768,-32768,-32768,-32768,-32768,    31,    31,     9,
    66,-32768,-32768,    72,-32768,-32768,    76,     9,-32768,-32768,
-32768,-32768,     9,-32768,   101,   105,-32768
};

static const short yypgoto[] = {-32768,
-32768,   -18,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
    54,    32,    15,-32768,-32768,    -1,    84,   -28,   -35,   -37,
-32768,   -14,    34,    26,    81
};


#define	YYLAST		110


static const short yytable[] = {    14,
    38,    65,    32,    37,    66,    69,    70,    48,    37,    69,
    70,     2,    67,    69,    70,    56,     3,    14,    73,    71,
    27,    28,    17,    87,    18,    29,    68,    92,    15,    30,
     4,    88,    89,    90,    20,     5,    40,     6,    27,    28,
    54,    28,    22,    29,    23,    29,    86,    41,    24,    30,
    57,    58,    95,    96,    98,    42,    43,    91,    59,    57,
    58,    72,    47,    14,   103,    80,    57,    58,    57,    58,
    50,    97,    80,    60,    61,    72,    74,    57,    58,   101,
    57,    58,    52,    51,   104,    83,    84,    85,    14,    17,
    81,    82,    22,    62,    63,    64,    14,    75,    76,    77,
   106,    14,    79,   100,   107,    78,    49,    93,    99,    55
};

static const short yycheck[] = {     1,
    19,    39,    17,    18,    40,     4,     5,    22,    23,     4,
     5,     3,    41,     4,     5,    30,     8,    19,    47,    18,
     8,     9,    19,    18,    21,    13,    41,    18,     8,    17,
    22,    69,    70,    71,    17,    27,     6,    29,     8,     9,
     8,     9,    19,    13,    21,    13,    65,    17,    19,    17,
    12,    13,    88,    89,    92,    25,    26,    72,    20,    12,
    13,     7,    17,    65,   102,    18,    12,    13,    12,    13,
     9,    90,    18,    14,    15,     7,    20,    12,    13,    98,
    12,    13,    11,    21,   103,    60,    61,    62,    90,    19,
    57,    58,    19,    16,    10,    23,    98,    10,    20,     9,
     0,   103,    10,    28,     0,    52,    23,    76,    94,    29
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 72 "threeaddr.y"
{
			blocknum++;
			blocks.push_back(blocknum);
			vars.push_back(varnum);
			varnum=0;
		;
    break;}
case 2:
#line 79 "threeaddr.y"
{
			for(map<ll,string>::iterator it=instList.begin();it!=instList.end();it++)
			{
				cout<<it->first<<" "<<it->second<<endl;
			}
		;
    break;}
case 3:
#line 86 "threeaddr.y"
{yyval.node=new NODE();yyval.node->nextList=yyvsp[0].node->nextList;;
    break;}
case 4:
#line 87 "threeaddr.y"
{yyval.node=new NODE();yyval.node->nextList=yyvsp[0].node->nextList;;
    break;}
case 5:
#line 88 "threeaddr.y"
{yyval.node=new NODE();yyval.node->nextList=yyvsp[0].node->nextList;;
    break;}
case 6:
#line 89 "threeaddr.y"
{yyval.node=new NODE();yyval.node->nextList=yyvsp[0].node->nextList;;
    break;}
case 7:
#line 90 "threeaddr.y"
{yyval.node=new NODE();yyval.node->nextList=yyvsp[0].node->nextList;;
    break;}
case 8:
#line 91 "threeaddr.y"
{yyval.node=new NODE();yyval.node->nextList=yyvsp[0].node->nextList;;
    break;}
case 9:
#line 93 "threeaddr.y"
{
								yyval.node=new NODE();
								backpatch(yyvsp[-3].node->trueList,yyvsp[-1].node->instNum);
								yyval.node->nextList=merge(yyvsp[-3].node->falseList,yyvsp[0].node->nextList);
							;
    break;}
case 10:
#line 98 "threeaddr.y"
{
											yyval.node=new NODE();
											backpatch(yyvsp[-7].node->trueList,yyvsp[-5].node->instNum);
											backpatch(yyvsp[-7].node->falseList,yyvsp[-1].node->instNum);
											yyval.node->nextList=merge(yyvsp[-4].node->nextList,yyvsp[-2].node->nextList);
											yyval.node->nextList=merge(yyval.node->nextList,yyvsp[0].node->nextList);
										;
    break;}
case 11:
#line 105 "threeaddr.y"
{
									yyval.node=new NODE();
									backpatch(yyvsp[-3].node->trueList,yyvsp[-1].node->instNum);
									backpatch(yyvsp[0].node->nextList,yyvsp[-5].node->instNum);
									instList[nextInst()]="goto "+to_string(yyvsp[-5].node->instNum);
									yyval.node->nextList=yyvsp[-3].node->falseList;
								;
    break;}
case 12:
#line 112 "threeaddr.y"
{
			blocknum++;
			blocks.push_back(blocknum);
			for(int i=0;i<s.size();i++)
			{
				insertID(blocknum,s[i]);
			}
			vars.push_back(varnum);
			varnum=0;
		;
    break;}
case 13:
#line 123 "threeaddr.y"
{
			blocks.pop_back();
			for(int i=0;i<varnum;i++)
				s.pop_back();
			varnum=vars.back();
			vars.pop_back();	
			yyval.node=new NODE();
			yyval.node->nextList=yyvsp[-1].node->nextList;
		;
    break;}
case 14:
#line 132 "threeaddr.y"
{
								yyval.node=new NODE();
								backpatch(yyvsp[-2].node->nextList,yyvsp[-1].node->instNum);
								yyval.node->nextList=yyvsp[0].node->nextList;
							;
    break;}
case 15:
#line 137 "threeaddr.y"
{yyval.node->nextList=yyvsp[0].node->nextList;;
    break;}
case 16:
#line 138 "threeaddr.y"
{
				varnum++;s.push_back(*yyvsp[-1].str+" "+*yyvsp[0].str);
				insertID(blocks.back(),*yyvsp[-1].str+" "+*yyvsp[0].str);
			;
    break;}
case 17:
#line 141 "threeaddr.y"
{yyval.node=new NODE();;
    break;}
case 18:
#line 143 "threeaddr.y"
{yyval.str=new string(*yyvsp[-1].str+*yyvsp[0].str);;
    break;}
case 19:
#line 143 "threeaddr.y"
{yyval.str=new string(*yyvsp[-3].str+*yyvsp[-2].str+*yyvsp[-1].str+*yyvsp[0].str);;
    break;}
case 20:
#line 145 "threeaddr.y"
{yyval.str=new string(*yyvsp[-3].str+*yyvsp[-2].str+*yyvsp[-1].str+*yyvsp[0].str);;
    break;}
case 21:
#line 145 "threeaddr.y"
{yyval.str=new string("");;
    break;}
case 22:
#line 147 "threeaddr.y"
{
			varnum++;s.push_back(*yyvsp[0].str);
			insertID(blocks.back(),*yyvsp[0].str);
		;
    break;}
case 24:
#line 150 "threeaddr.y"
{;
    break;}
case 25:
#line 152 "threeaddr.y"
{instList[nextInst()]=yyvsp[-3].node->array+"["+yyvsp[-3].node->addr+"]= "+yyvsp[-1].node->addr;	;
    break;}
case 26:
#line 153 "threeaddr.y"
{
	  					if(table[blocks.back()].find(*yyvsp[-3].str)==table[blocks.back()].end())
						{
							yyerror("variable not declared");
						}
	  					instList[nextInst()]=*yyvsp[-3].str+" = "+yyvsp[-1].node->addr;
	  					yyval.node=new NODE();
	  				;
    break;}
case 27:
#line 162 "threeaddr.y"
{
					yyval.node=makeNode();
					yyval.node->array=*yyvsp[-3].str;
					if(table[blocks.back()].find(*yyvsp[-3].str)==table[blocks.back()].end())
					{
						yyerror("variable not declared");
					}
					yyval.node->type=table[blocks.back()][*yyvsp[-3].str].first;
					instList[nextInst()]=yyval.node->addr+" = "+yyvsp[-1].node->addr+" * "+to_string(getWidth(yyval.node->type));
				;
    break;}
case 28:
#line 173 "threeaddr.y"
{
		 			NODE *myTemp=makeNode();
		 			yyval.node=makeNode();
		 			yyval.node->array=yyvsp[-3].node->array;
		 			yyval.node->type=yyvsp[-3].node->type;
		 			yyval.node->type.second.erase(yyval.node->type.second.begin());
		 			instList[nextInst()]=myTemp->addr + " = "+yyvsp[-1].node->addr +" * "+to_string(getWidth(yyval.node->type));
		 			instList[nextInst()]=yyval.node->addr+" = "+yyvsp[-3].node->addr+ " + " + myTemp->addr;
		 		;
    break;}
case 29:
#line 182 "threeaddr.y"
{yyval.node=yyvsp[0].node;;
    break;}
case 30:
#line 185 "threeaddr.y"
{
					yyval.node=new NODE();
					backpatch(yyvsp[-3].node->falseList,yyvsp[-1].node->instNum);
					yyval.node->trueList=merge(yyvsp[-3].node->trueList,yyvsp[0].node->trueList);
					yyval.node->falseList=yyvsp[0].node->falseList;
				;
    break;}
case 31:
#line 191 "threeaddr.y"
{
	 				yyval.node=new NODE();
	 				backpatch(yyvsp[-3].node->trueList,yyvsp[-1].node->instNum);
	 				yyval.node->trueList=yyvsp[0].node->trueList;
	 				yyval.node->falseList=merge(yyvsp[-3].node->falseList,yyvsp[0].node->falseList);
				;
    break;}
case 32:
#line 197 "threeaddr.y"
{yyval.node=new NODE();yyval.node->trueList=yyvsp[0].node->trueList;yyval.node->falseList=yyvsp[0].node->falseList;;
    break;}
case 33:
#line 199 "threeaddr.y"
{yyval.node=new NODE();yyval.node->trueList=yyvsp[0].node->falseList;yyval.node->falseList=yyvsp[0].node->trueList;;
    break;}
case 34:
#line 200 "threeaddr.y"
{yyval.node=new NODE();yyval.node->trueList=yyvsp[-1].node->trueList;yyval.node->falseList=yyvsp[-1].node->falseList;;
    break;}
case 35:
#line 201 "threeaddr.y"
{
	    				yyval.node=new NODE();
	    				yyval.node->trueList.push_back(nextInst());
	    				instList[yyval.node->trueList.back()]="if("+yyvsp[-2].node->addr+" "+*yyvsp[-1].str+" "+yyvsp[0].node->addr+") goto";
	    				yyval.node->falseList.push_back(nextInst());
	    				instList[yyval.node->falseList.back()]="goto";
	    			;
    break;}
case 36:
#line 208 "threeaddr.y"
{yyval.node=new NODE();yyval.node->trueList.push_back(nextInst());instList[yyval.node->trueList.back()]="goto";;
    break;}
case 37:
#line 209 "threeaddr.y"
{yyval.node=new NODE();yyval.node->falseList.push_back(nextInst());instList[yyval.node->falseList.back()]="goto";;
    break;}
case 38:
#line 210 "threeaddr.y"
{yyval.node=new NODE();yyval.node=new NODE();yyval.node->instNum=instCounter;;
    break;}
case 39:
#line 211 "threeaddr.y"
{yyval.node=new NODE();yyval.node->nextList.push_back(nextInst());instList[yyval.node->nextList.back()]="goto";;
    break;}
case 40:
#line 213 "threeaddr.y"
{yyval.node=makeNode();instList[nextInst()]=yyval.node->addr+" = "+yyvsp[-2].node->addr+" + "+yyvsp[0].node->addr;;
    break;}
case 41:
#line 214 "threeaddr.y"
{yyval.node=makeNode();instList[nextInst()]=yyval.node->addr+" = "+yyvsp[-2].node->addr+" - "+yyvsp[0].node->addr;;
    break;}
case 42:
#line 215 "threeaddr.y"
{yyval.node=yyvsp[0].node;;
    break;}
case 43:
#line 216 "threeaddr.y"
{yyval.node=makeNode();instList[nextInst()]=yyval.node->addr+" = "+yyvsp[0].node->array+"["+yyvsp[0].node->addr+"]";;
    break;}
case 44:
#line 218 "threeaddr.y"
{yyval.node=makeNode();instList[nextInst()]=yyval.node->addr+" = "+yyvsp[-2].node->addr+" * "+yyvsp[0].node->addr;;
    break;}
case 45:
#line 219 "threeaddr.y"
{yyval.node=makeNode();instList[nextInst()]=yyval.node->addr+" = "+yyvsp[-2].node->addr+" / "+yyvsp[0].node->addr;;
    break;}
case 46:
#line 220 "threeaddr.y"
{yyval.node=yyvsp[0].node;;
    break;}
case 47:
#line 222 "threeaddr.y"
{yyval.node=makeNode();instList[nextInst()]=yyval.node->addr+" = "+yyvsp[-2].node->addr+" ^ "+yyvsp[0].node->addr;;
    break;}
case 48:
#line 223 "threeaddr.y"
{yyval.node=yyvsp[0].node;;
    break;}
case 49:
#line 225 "threeaddr.y"
{yyval.node=yyvsp[-1].node;;
    break;}
case 50:
#line 226 "threeaddr.y"
{
	 		if(table[blocks.back()].find(*yyvsp[0].str)==table[blocks.back()].end())
			{
				yyerror("variable not declared");
			}
			yyval.node=makeNode(yyvsp[0].str);
		;
    break;}
case 51:
#line 233 "threeaddr.y"
{yyval.node=makeNode(yyvsp[0].str);;
    break;}
case 52:
#line 234 "threeaddr.y"
{yyval.node=makeNode();instList[nextInst()]=yyval.node->addr+" = - "+yyvsp[0].node->addr;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 236 "threeaddr.y"

int nextInst()
{
	return instCounter++;
}
vector<ll> merge(vector<ll> a,vector<ll> b)
{
	a.insert(a.end(),b.begin(),b.end());
	return a;
}
void backpatch(vector<ll> list,int num)
{
	for(ll i=0;i<list.size();i++)
	{
		if(instList[list[i]].find("goto")==instList[list[i]].length()-4)
		{
			instList[list[i]]+=" "+to_string(num);
		}
	}
}
void insertID(int bno,string varname)
{
	string type,value;
	int ind=varname.find(" ");
	if(ind!=-1)
	{
		type=varname.substr(0,ind);
		varname=varname.substr(ind+1);
	}
	ind=varname.find("=");
	value="";
	if(ind!=-1)
	{
		value=varname.substr(ind+1);
		varname=varname.substr(0,ind);
	}
	ind=varname.find("[");
	vector<ll> dims;
	if(ind!=-1)
	{
		string indexes=varname.substr(ind);
		varname=varname.substr(0,ind);
		for(ll i=0;i<indexes.length();i++)
		{
			if(indexes[i]=='[' || indexes[i]==']')
				indexes[i]=' ';
		}
		istringstream in(indexes.c_str());
		int dim;
		while(in>>dim)
		{
			dims.push_back(dim);
		}
	}
	table[bno][varname]=make_pair(make_pair(type,dims),value);
}
ll getWidth(pair<string,vector<ll> > type)
{
	ll ans=width[type.first];
	for(ll i=1;i<type.second.size();i++)
	{
		ans=ans*type.second[i];
	}
	return ans;
}
void printTable()
{
	for(map<ll,map<string,pair<pair<string,vector<ll> >,string> > >::iterator it=table.begin();it!=table.end();it++)
	{
		cout<<it->first<<endl;
		for(map<string,pair<pair<string,vector<ll> >,string> >::iterator it2=it->second.begin();it2!=it->second.end();it2++)
		{
			cout<<it2->first<<" "<<it2->second.first.first<<" "<<it2->second.second;
			for(vector<ll>::iterator it3=it2->second.first.second.begin();it3!=it2->second.first.second.end();it3++)
				cout<<*it3<<' ';
			cout<<endl;
		}
		cout<<endl;
	}
}
void setWidths()
{
	width["int"]=4;
	width["float"]=4;
	width["char"]=1;
	width["double"]=8;
}
string to_string(ll val)
{
	ostringstream ss;
	ss<<val;
	return ss.str();
}
void yyerror(char* s)
{
	cout<<s<<endl;
	exit(0);
}
int main()
{
	setWidths();
	yyparse();
}
